=== zycgit/dbvisitor/dbvisitor-doc/static/schema/dbvisitor-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
       Copyright 2015-2022 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.
-->
<!ELEMENT mapper ( resultMap* | entity* | sql* | execute* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
        namespace CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        >

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
        id CDATA #IMPLIED
        type CDATA #REQUIRED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT result EMPTY>
<!ATTLIST result
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT entity (id*,mapping*,index*)>
<!ATTLIST entity
        id CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED
        table CDATA #IMPLIED
        type CDATA #REQUIRED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        ddlAuto (none|create|add|update|create-drop) #IMPLIED
        >

<!ELEMENT id EMPTY>
<!ATTLIST id
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        orderByColTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        groupByColTemplate CDATA #IMPLIED
        orderByColTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        nullable (true|false) #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT index (column* | EMPTY)>
<!ATTLIST index
        name CDATA #REQUIRED
        columns CDATA #IMPLIED
        unique (true|false) #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT column (#PCDATA)>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        useGeneratedKeys CDATA #IMPLIED
        generatedKeySource CDATA #IMPLIED
        keyProperty CDATA #IMPLIED
        keyColumn CDATA #IMPLIED
        >

<!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT execute (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST execute
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        bindOut CDATA #IMPLIED
        >

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        resultSetExtractor CDATA #IMPLIED
        resultRowCallback CDATA #IMPLIED
        resultRowMapper CDATA #IMPLIED
        resultTypeHandler CDATA #IMPLIED
        bindOut CDATA #IMPLIED
        >

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        >

<!-- Dynamic -->
<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
    <!ATTLIST selectKey
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType CDATA #IMPLIED
        keyProperty CDATA #REQUIRED
        keyColumn CDATA #IMPLIED
        order (BEFORE|AFTER) #REQUIRED
        >

<!ELEMENT include EMPTY>
<!ATTLIST include
        refid CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        >

<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        item CDATA #REQUIRED
        index CDATA #IMPLIED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>

<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
        test CDATA #REQUIRED
        >

<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
        test CDATA #REQUIRED
        >

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/redis/NativeMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="redis.Native">
    <resultMap id="entry" type="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisNativeMapperSupport$Entry">
        <result column="FIELD" property="field"/>
        <result column="VALUE" property="value" javaType="java.lang.String"/>
    </resultMap>
    <insert id="put">SET #{key} #{value}</insert>
    <update id="replace">SET #{key} #{value} XX</update>
    <delete id="remove">DEL #{key}</delete>
    <select id="get" resultType="java.lang.String">GET #{key}</select>
    <select id="list" resultType="java.lang.String">LRANGE #{key} 0 -1</select>
    <select id="entries" resultMap="entry">HGETALL #{key}</select>
    <select id="maps" resultType="java.util.Map">HGETALL #{key}</select>
    <select id="mapped" resultRowMapper="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisNativeMapperSupport$ValuesMapper"> LRANGE #{key} 0 -1 </select>
    <select id="extracted" resultSetExtractor="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisNativeMapperSupport$ValuesExtractor"> LRANGE #{key} 0 -1 </select>
    <select id="options" resultType="java.lang.String" timeout="5" fetchSize="1" resultSetType="FORWARD_ONLY"> LRANGE #{key} 0 -1 </select>
    <select id="statement" resultType="java.lang.String" statementType="STATEMENT">PING</select>
    <insert id="conditional"> SET #{key} #{value} <if test="existing != null and existing">XX</if> </insert>
    <select id="choose" resultType="java.lang.String"> <choose> <when test="single">LINDEX #{key} 0</when> <otherwise>LRANGE #{key} 0 -1</otherwise> </choose> </select>
    <select id="many" resultType="java.util.Map"> MGET <foreach collection="keyList" item="item" separator=" ">#{item}</foreach> </select>
    <insert id="manyPut"> MSET <foreach collection="items" item="item" separator=" ">#{item.key} #{item.value}</foreach> </insert>
    <delete id="manyRemove"> DEL <foreach collection="keyList" item="item" separator=" ">#{item}</foreach> </delete>
    <select id="bound" resultType="java.lang.String"> <bind name="fullKey" value="prefix + suffix"/> GET #{fullKey} </select>
    <insert id="before"> <selectKey keyProperty="id" order="BEFORE">INCR #{counter}</selectKey> HSET #{key} #{id} #{value} </insert>
    <insert id="after"> <selectKey keyProperty="id" order="AFTER">LLEN #{key}</selectKey> RPUSH #{key} #{value} </insert>
    <insert id="resultKey" useGeneratedKeys="true" generatedKeySource="resultSet" keyProperty="id" keyColumn="VALUE"> INCR #{counter} </insert>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/oneapi/session/UserSessionMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="oneapi.session.UserSessionMapper">

    <resultMap id="userInfoMap" type="net.hasor.dbvisitor.test.oneapi.model.UserInfo">
        <result column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <resultMap id="orderMap" type="net.hasor.dbvisitor.test.oneapi.model.UserOrder">
        <result column="id" property="id"/>
        <result column="user_id" property="userId"/>
        <result column="order_no" property="orderNo"/>
        <result column="amount" property="amount"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <resultMap id="orderDtoMap" type="net.hasor.dbvisitor.test.oneapi.model.UserOrderDTO">
        <result column="order_id" property="orderId"/>
        <result column="order_no" property="orderNo"/>
        <result column="amount" property="amount"/>
        <result column="create_time" property="createTime"/>
        <result column="user_id" property="userId"/>
        <result column="user_name" property="userName"/>
        <result column="user_email" property="userEmail"/>
    </resultMap>

    <!-- ========== user_info CRUD ========== -->

    <insert id="insertUser">
        insert into user_info (id, name, age, email, create_time)
        values (#{id}, #{name}, #{age}, #{email}, CURRENT_TIMESTAMP)
    </insert>

    <select id="queryUserById" resultMap="userInfoMap">
        select * from user_info where id = #{id}
    </select>

    <select id="queryAllUsers" resultMap="userInfoMap">
        select * from user_info order by id asc
    </select>

    <select id="queryUsersByAge" resultMap="userInfoMap">
        select * from user_info where age = #{age} order by id asc
    </select>

    <select id="countUsers" resultType="int">
        select count(*) from user_info
    </select>

    <update id="updateUserEmail">
        update user_info set email = #{email} where id = #{id}
    </update>

    <delete id="deleteUserById">
        delete from user_info where id = #{id}
    </delete>

    <!-- ========== user_order CRUD ========== -->

    <insert id="insertOrder">
        insert into user_order (id, user_id, order_no, amount, create_time)
        values (#{id}, #{userId}, #{orderNo}, #{amount}, CURRENT_TIMESTAMP)
    </insert>

    <select id="queryOrdersByUserId" resultMap="orderMap">
        select * from user_order where user_id = #{userId} order by id asc
    </select>

    <delete id="deleteOrderById">
        delete from user_order where id = #{id}
    </delete>

    <!-- ========== JOIN 查询 ========== -->

    <select id="queryOrderWithUser" resultMap="orderDtoMap">
        select o.id as order_id, o.order_no, o.amount, o.create_time,
               u.id as user_id, u.name as user_name, u.email as user_email
        from user_order o
        left join user_info u on o.user_id = u.id
        where o.id = #{orderId}
    </select>

    <!-- ========== 动态条件查询 ========== -->

    <select id="queryUsersByCondition" resultMap="userInfoMap">
        select * from user_info
        where 1=1
        @{and, name = :name}
        @{and, age = :age}
        order by id asc
    </select>

    <!-- ========== Bean 参数 ========== -->

    <select id="queryUserByBean" resultMap="userInfoMap">
        select * from user_info where name = #{name} and age = #{age}
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapping/basic_entity_mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.mapping">

    <!-- 基本 entity 测试: 完整属性配置 -->
    <entity id="FullEntity" table="user_info" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo"
            catalog="test_cat" schema="test_sch"
            ddlAuto="create" character-set="utf8mb4" collation="utf8mb4_general_ci"
            comment="user table" other="ENGINE=InnoDB">
        <id column="id" property="id" keyType="auto"/>
        <mapping column="name" property="name"/>
        <mapping column="age" property="age" insert="false"/>
        <mapping column="email" property="email" update="false"/>
        <mapping column="create_time" property="createTime"/>
        <index name="idx_name" columns="name"/>
        <index name="idx_email_age" columns="email,age" unique="true" comment="composite index"/>
    </entity>

    <!-- 基本 resultMap 测试 -->
    <resultMap id="SimpleResultMap" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <result column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <!-- autoMapping=false, 只映射部分列 -->
    <entity id="PartialEntity" table="user_info" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo"
            autoMapping="false">
        <id column="id" property="id"/>
        <mapping column="name" property="name"/>
    </entity>

    <!-- 使用 column description 属性 -->
    <entity id="DescEntity" table="user_info" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id" sqlType="BIGINT"/>
        <mapping column="name" property="name" sqlType="VARCHAR" length="128" default="'unknown'" comment="user name"/>
        <mapping column="age" property="age" precision="10" scale="0"/>
    </entity>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/milvus/material/XmlCapabilityCrudMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.CrudMapper">
    <select id="selectAll" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        SELECT id, name, age, email, create_time FROM user_info ORDER BY v &lt;-&gt; [0, 0]
    </select>
    <select id="selectForPage" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        SELECT id, name, age, email, create_time FROM user_info ORDER BY v &lt;-&gt; [0, 0]
    </select>
    <select id="selectById" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        SELECT id, name, age, email, create_time FROM user_info WHERE id = #{id}
    </select>
    <select id="selectAllAsMap" resultType="java.util.Map">
        SELECT id, name, age, email, create_time FROM user_info
    </select>
    <select id="selectNames" resultType="java.lang.String">
        SELECT name FROM user_info ORDER BY v &lt;-&gt; [0, 0]
    </select>
    <select id="countAll" resultType="java.lang.Integer">COUNT FROM user_info</select>
    <delete id="deleteByName">DELETE FROM user_info WHERE name = #{name}</delete>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/session/RedisResultSessionMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="session.UserSessionMapper">
    <resultMap id="entry" type="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisMappedEntry" autoMapping="false">
        <result column="SCORE" property="field" javaType="java.lang.Integer"/>
        <result column="ELEMENT" property="value"/>
    </resultMap>
    <select id="insertUser" resultSetExtractor="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisIntegerResultExtractor"> EVAL "local added=redis.call('ZADD',KEYS[1],ARGV[1],ARGV[2]); redis.call('ZADD',KEYS[2],ARGV[3],ARGV[2]); return added" 2 @{macro, redisUsers} @{macro, redisAges} #{id} #{name} #{age} </select>
    <select id="queryUserById" resultMap="entry">ZRANGEBYSCORE @{macro, redisUsers} #{id} #{id} WITHSCORES</select>
    <select id="queryUsersByAge" resultMap="entry">ZRANGEBYSCORE @{macro, redisAges} #{age} #{age} WITHSCORES</select>
    <select id="queryAllUsers" resultMap="entry">ZRANGE @{macro, redisUsers} 0 -1 WITHSCORES</select>
    <select id="countUsers" resultType="java.lang.Integer">ZCARD @{macro, redisUsers}</select>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/mongo/DynamicSqlMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.DynamicSqlMapper">
    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <select id="selectWithIf" resultMap="userResultMap">
        @{macro, mongoSource}.find({
            <trim suffixOverrides=",">
                name: {$regex: '^DynSql'},
                <if test="minAge != null">age: {$gte: #{minAge}},</if>
                <if test="email != null">email: #{email},</if>
            </trim>
        }, {_id: 0}).sort({id: 1})
    </select>
    <select id="selectWithChoose" resultMap="userResultMap">
        @{macro, mongoSource}.find({name: {$regex: '^DynSql'}}, {_id: 0}).sort({
            <choose>
                <when test="orderBy == 'name'">name: 1</when>
                <when test="orderBy == 'age'">age: -1</when>
                <otherwise>id: 1</otherwise>
            </choose>
        })
    </select>
    <sql id="exactCondition">
        <trim prefixOverrides="," suffixOverrides=",">
            <if test="name != null">, name: #{name}</if>
            <if test="age != null">, age: #{age}</if>
            <if test="email != null">, email: #{email}</if>
        </trim>
    </sql>
    <select id="selectWithWhere" resultMap="userResultMap">
        @{macro, mongoSource}.find({<include refid="exactCondition"/>}, {_id: 0}).sort({id: 1})
    </select>
    <select id="selectWithTrim" resultMap="userResultMap">
        @{macro, mongoSource}.find({<include refid="exactCondition"/>}, {_id: 0}).sort({id: 1})
    </select>
    <update id="updateWithSet">
        @{macro, mongoSource}.update({id: #{id}}, {$set: {
            <trim suffixOverrides=",">
                <if test="name != null">name: #{name},</if>
                <if test="age != null">age: #{age},</if>
                <if test="email != null">email: #{email},</if>
            </trim>
        }})
    </update>
    <select id="selectByIdList" resultMap="userResultMap">
        @{macro, mongoSource}.find({id: {$in:
            <foreach collection="ids" item="id" open="[" separator="," close="]">#{id}</foreach>
        }}, {_id: 0}).sort({id: 1})
    </select>
    <insert id="batchInsert">
        @{macro, mongoSource}.insert([
            <foreach collection="users" item="u" separator=",">
                {id: #{u.id}, name: #{u.name}, age: #{u.age}, email: #{u.email}}
            </foreach>
        ])
    </insert>
    <select id="selectWithBind" resultMap="userResultMap">
        <bind name="namePattern" value="'.*' + name + '.*'"/>
        @{macro, mongoSource}.find({name: {$regex: #{namePattern}}}, {_id: 0}).sort({id: 1})
    </select>
    <select id="selectWithBoundAge" resultMap="userResultMap">
        <bind name="ageFloor" value="minAge + 1"/>
        @{macro, mongoSource}.find({name: {$regex: '^DynSql'}, age: {$gte: #{ageFloor}}}, {_id: 0}).sort({id: 1})
    </select>
    <select id="selectComplex" resultMap="userResultMap">
        @{macro, mongoSource}.find({
            <trim suffixOverrides=",">
                <if test="name != null">
                    $expr: {$regexMatch: {input: '$name', regex: {$replaceAll: {input: #{name}, find: '%', replacement: '.*'}}}},
                </if>
                <if test="ids != null">
                    id: {$in:
                        <foreach collection="ids" item="id" open="[" separator="," close="]">#{id}</foreach>
                    },
                </if>
            </trim>
        }, {_id: 0}).sort({id: 1})
    </select>
    <select id="selectByAgeCategory" resultMap="userResultMap">
        @{macro, mongoSource}.find({name: {$regex: '^DynSql'}, age: {
            <choose>
                <when test="category == 'young'">$lt: 30</when>
                <when test="category == 'middle'">$gte: 30, $lte: 40</when>
                <otherwise>$gt: 40</otherwise>
            </choose>
        }}, {_id: 0}).sort({id: 1})
    </select>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/XmlJoinQueryMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.JoinQueryMapper">

    <resultMap id="userOrderDTOMap" type="net.hasor.dbvisitor.test.contract.material.model.UserOrderDTO">
        <result column="order_id" property="orderId"/>
        <result column="order_no" property="orderNo"/>
        <result column="amount" property="amount"/>
        <result column="order_create_time" property="createTime"/>
        <result column="user_id" property="userId"/>
        <result column="user_name" property="userName"/>
        <result column="user_email" property="userEmail"/>
    </resultMap>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <insert id="insertOrder">
        INSERT INTO user_order (id, user_id, order_no, amount, create_time)
        VALUES (#{id}, #{userId}, #{orderNo}, #{amount}, @{macro, currentTimestamp})
    </insert>

    <!-- INNER JOIN：映射到 DTO -->
    <select id="selectUserOrderDTO" resultMap="userOrderDTOMap">
        SELECT
            o.id AS order_id,
            o.order_no AS order_no,
            o.amount AS amount,
            o.create_time AS order_create_time,
            u.id AS user_id,
            u.name AS user_name,
            u.email AS user_email
        FROM user_order o
        INNER JOIN user_info u ON o.user_id = u.id
        WHERE u.id = #{userId}
        ORDER BY o.id
    </select>

    <!-- INNER JOIN：映射到 Map -->
    <select id="selectUserOrderMap" resultType="map">
        SELECT
            o.id AS order_id,
            o.order_no,
            o.amount,
            u.id AS user_id,
            u.name AS user_name,
            u.email AS user_email
        FROM user_order o
        INNER JOIN user_info u ON o.user_id = u.id
        WHERE u.id = #{userId}
        ORDER BY o.id
    </select>

    <!-- LEFT JOIN：无匹配行时 null 处理 -->
    <select id="selectUserOrderLeftJoin" resultType="map">
        SELECT
            u.id AS user_id,
            u.name AS user_name,
            o.id AS order_id,
            o.order_no
        FROM user_info u
        LEFT JOIN user_order o ON u.id = o.user_id
        WHERE u.id = #{userId}
    </select>

    <!-- 聚合函数 + GROUP BY -->
    <select id="selectUserOrderAggregate" resultType="map">
        SELECT
            u.id AS user_id,
            u.name AS user_name,
            COUNT(o.id) AS order_count,
            COALESCE(SUM(o.amount), 0) AS total_amount
        FROM user_info u
        LEFT JOIN user_order o ON u.id = o.user_id
        WHERE u.id = #{userId}
        GROUP BY u.id, u.name
    </select>

    <!-- 自连接 -->
    <select id="selectSameAgeUsers" resultType="map">
        SELECT
            u1.id AS user1_id,
            u1.name AS user1_name,
            u2.id AS user2_id,
            u2.name AS user2_name,
            u1.age AS common_age
        FROM user_info u1
        INNER JOIN user_info u2 ON u1.age = u2.age AND u1.id &lt; u2.id
        WHERE u1.name LIKE 'JoinQ%' AND u2.name LIKE 'JoinQ%'
        ORDER BY u1.age, u1.id
    </select>

    <!-- 子查询 -->
    <select id="selectUsersWithOrders" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        SELECT * FROM user_info
        WHERE id IN (
            SELECT DISTINCT user_id FROM user_order
        )
        AND name LIKE 'JoinQ%'
        ORDER BY id
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/mongo/BaseMapperStatements.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="StatementTestMapper">
    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <insert id="insertUserWithId">
        @{macro, mongoSource}.insert({id: #{id}, name: #{name}, age: #{age}, email: #{email}, create_time: 1700000000000})
    </insert>
    <update id="updateUserEmail">
        @{macro, mongoSource}.update({id: #{id}}, {$set: {email: #{email}}})
    </update>
    <delete id="deleteUserById">
        @{macro, mongoSource}.remove({id: #{id}})
    </delete>
    <delete id="deleteUsersByName">
        @{macro, mongoSource}.remove({$expr: {$regexMatch: {input: '$name', regex: {$replaceAll: {input: #{name}, find: '%', replacement: '.*'}}}}})
    </delete>
    <select id="queryUserById" resultMap="userResultMap">
        @{macro, mongoSource}.find({id: #{id}}, {_id: 0})
    </select>
    <select id="queryUsersByName" resultMap="userResultMap">
        @{macro, mongoSource}.find({$expr: {$regexMatch: {input: '$name', regex: {$replaceAll: {input: #{name}, find: '%', replacement: '.*'}}}}}, {_id: 0}).sort({id: 1})
    </select>
    <select id="queryAllUsers" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        @{macro, mongoSource}.find({}, {_id: 0}).sort({id: 1})
    </select>
</mapper>
