=== zycgit/dbvisitor/dbvisitor-doc/static/schema/dbvisitor-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
       Copyright 2015-2022 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.
-->
<!ELEMENT mapper ( resultMap* | entity* | sql* | execute* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
        namespace CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        >

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
        id CDATA #IMPLIED
        type CDATA #REQUIRED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT result EMPTY>
<!ATTLIST result
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT entity (id*,mapping*,index*)>
<!ATTLIST entity
        id CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED
        table CDATA #IMPLIED
        type CDATA #REQUIRED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        ddlAuto (none|create|add|update|create-drop) #IMPLIED
        >

<!ELEMENT id EMPTY>
<!ATTLIST id
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        orderByColTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        groupByColTemplate CDATA #IMPLIED
        orderByColTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        nullable (true|false) #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT index (column* | EMPTY)>
<!ATTLIST index
        name CDATA #REQUIRED
        columns CDATA #IMPLIED
        unique (true|false) #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT column (#PCDATA)>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        useGeneratedKeys CDATA #IMPLIED
        generatedKeySource CDATA #IMPLIED
        keyProperty CDATA #IMPLIED
        keyColumn CDATA #IMPLIED
        >

<!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT execute (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST execute
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        bindOut CDATA #IMPLIED
        >

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        resultSetExtractor CDATA #IMPLIED
        resultRowCallback CDATA #IMPLIED
        resultRowMapper CDATA #IMPLIED
        resultTypeHandler CDATA #IMPLIED
        bindOut CDATA #IMPLIED
        >

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        >

<!-- Dynamic -->
<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
    <!ATTLIST selectKey
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType CDATA #IMPLIED
        keyProperty CDATA #REQUIRED
        keyColumn CDATA #IMPLIED
        order (BEFORE|AFTER) #REQUIRED
        >

<!ELEMENT include EMPTY>
<!ATTLIST include
        refid CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        >

<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        item CDATA #REQUIRED
        index CDATA #IMPLIED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>

<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
        test CDATA #REQUIRED
        >

<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
        test CDATA #REQUIRED
        >

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/mongo/KeyMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.KeyGenerationMapper">
    <insert id="insertWithGeneratedKeys" useGeneratedKeys="true" keyProperty="id">
        @{macro, mongoSource}.insert({name: #{name}})
    </insert>
    <insert id="insertWithKeyColumn" useGeneratedKeys="true" keyProperty="id" keyColumn="_ID">
        @{macro, mongoSource}.insert({name: #{name}})
    </insert>
    <insert id="insertWithSelectKeyBefore">
        <selectKey keyProperty="id" order="BEFORE">
            @{macro, mongoKeySource}.find({name: #{name}}, {_id: 1})
        </selectKey>
        @{macro, mongoSource}.insert({_id: ObjectId(#{id}), name: #{name}})
    </insert>
    <insert id="insertWithSelectKeyAfter">
        <selectKey keyProperty="id" order="AFTER">
            @{macro, mongoSource}.find({name: #{name}}, {_id: 1})
        </selectKey>
        @{macro, mongoSource}.insert({name: #{name}})
    </insert>
    <select id="selectById" resultType="string">
        @{macro, mongoSource}.find({_id: ObjectId(#{id})}, {_id: 0, name: 1})
    </select>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/mongo/QueryMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.CrudMapper">
    <select id="selectAll" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        @{macro, mongoSource}.find({}, {_id: 0}).sort({id: 1})
    </select>
    <select id="selectById" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        @{macro, mongoSource}.find({id: #{id}}, {_id: 0})
    </select>
    <delete id="deleteByName">
        @{macro, mongoSource}.remove({name: #{name}})
    </delete>
    <select id="selectAllAsMap" resultType="java.util.Map">
        @{macro, mongoSource}.find({}, {_id: 0}).sort({id: 1})
    </select>
    <select id="countAll" resultType="int">
        @{macro, mongoSource}.count({})
    </select>
    <select id="selectNames" resultType="string">
        @{macro, mongoSource}.find({}, {_id: 0, name: 1}).sort({id: 1})
    </select>
    <select id="selectForPage" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        @{macro, mongoSource}.find({}, {_id: 0}).sort({id: 1})
    </select>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/mongo/SessionRefMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.dbvisitor.test.realdb.mongo.material.MongoSessionRefMapper">
    <select id="queryOrderWithUser" resultType="net.hasor.dbvisitor.test.contract.material.model.UserOrderDTO">
        @{macro, mongoOrders}.aggregate([
            {$match: {id: #{orderId}}},
            {$lookup: {from: '@{macro, mongoCollection}', localField: 'user_id', foreignField: 'id', as: 'user'}},
            {$unwind: {path: '$user', preserveNullAndEmptyArrays: true}},
            {$project: {_id: 0, orderId: '$id', orderNo: '$order_no', amount: 1, createTime: '$create_time',
                        userId: '$user.id', userName: '$user.name', userEmail: '$user.email'}}
        ])
    </select>
    <resultMap id="userInfoMap" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <result column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>
    <resultMap id="orderMap" type="net.hasor.dbvisitor.test.contract.material.model.UserOrder">
        <result column="id" property="id"/>
        <result column="user_id" property="userId"/>
        <result column="order_no" property="orderNo"/>
        <result column="amount" property="amount"/>
    </resultMap>
    <insert id="insertUser">
        @{macro, mongoSource}.insert({id: #{id}, name: #{name}, age: #{age}, email: #{email}})
    </insert>
    <select id="queryUserById" resultMap="userInfoMap">
        @{macro, mongoSource}.find({id: #{id}}, {_id: 0})
    </select>
    <select id="queryAllUsers" resultMap="userInfoMap">
        @{macro, mongoSource}.find({}, {_id: 0}).sort({id: 1})
    </select>
    <select id="queryUsersByAge" resultMap="userInfoMap">
        @{macro, mongoSource}.find({age: #{age}}, {_id: 0}).sort({id: 1})
    </select>
    <select id="countUsers" resultType="int">
        @{macro, mongoSource}.count({})
    </select>
    <update id="updateUserEmail">
        @{macro, mongoSource}.update({id: #{id}}, {$set: {email: #{email}}})
    </update>
    <delete id="deleteUserById">
        @{macro, mongoSource}.remove({id: #{id}})
    </delete>
    <insert id="insertOrder">
        @{macro, mongoOrders}.insert({id: #{id}, user_id: #{userId}, order_no: #{orderNo}, amount: #{amount}})
    </insert>
    <select id="queryOrdersByUserId" resultMap="orderMap">
        @{macro, mongoOrders}.find({user_id: #{userId}}, {_id: 0}).sort({id: 1})
    </select>
    <delete id="deleteOrderById">
        @{macro, mongoOrders}.remove({id: #{id}})
    </delete>
    <select id="queryUsersByCondition" resultMap="userInfoMap">
        @{macro, mongoSource}.find({
        <if test="name != null">name: #{name},</if>
        <if test="age != null">age: #{age},</if>
        }, {_id: 0}).sort({id: 1})
    </select>
    <select id="queryUserByBean" resultMap="userInfoMap">
        @{macro, mongoSource}.find({name: #{name}, age: #{age}}, {_id: 0})
    </select>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/oneapi/mapper/KeyTypeMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="KeyTypeMapper">
    
    <!-- ========== Entity 配置示例 ========== -->
    
    <!-- 使用 keyType="auto" 的 entity -->
    <entity id="AutoKeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="uuid32" 的 entity -->
    <entity id="Uuid32KeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" keyType="uuid32" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="uuid36" 的 entity -->
    <entity id="Uuid36KeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" keyType="uuid36" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="Sequence::seq_name" 的 entity -->
    <entity id="SequenceKeyEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="Sequence::user_id_seq" />
        <mapping column="name" property="name" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 使用 keyType="完整类名" 的 entity（自定义 Holder） -->
    <entity id="CustomHolderEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="net.hasor.dbvisitor.test.oneapi.handler.keygen.FixedValueKeyHolder" />
        <mapping column="name" property="name" keyType="uuid36" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- 多个字段配置不同 keyType -->
    <entity id="MultiKeyTypesEntity" table="user_info" type="map">
        <id column="id" property="id" keyType="auto" />
        <mapping column="name" property="name" keyType="uuid32" />
        <mapping column="age" property="age" />
        <mapping column="create_time" property="createTime" />
    </entity>
    
    <!-- ========== ResultMap 配置示例 ========== -->
    
    <!-- ResultMap 中 <id> 标签配置 keyType -->
    <resultMap id="UserResultMapWithKeyType" type="map">
        <id column="id" property="id" keyType="auto" />
        <result column="name" property="name" />
        <result column="age" property="age" />
        <result column="create_time" property="createTime" />
    </resultMap>
    
    <!-- ResultMap 中 <result> 标签配置 keyType -->
    <resultMap id="UserResultMapMappingKeyType" type="map">
        <id column="id" property="id" keyType="auto" />
        <result column="name" property="name" keyType="uuid36" />
        <result column="age" property="age" />
        <result column="create_time" property="createTime" />
    </resultMap>
    
    <!-- ========== Insert 语句 ========== -->
    
    <insert id="insertAutoKeyUser" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertUuid32User">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertUuid36User">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertSequenceUser" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertCustomHolderUser">
        INSERT INTO user_info (id, name, age, create_time)
        VALUES (#{id}, #{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertWithResultMap" resultMap="UserResultMapWithKeyType" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertWithMappingKeyType" resultMap="UserResultMapMappingKeyType" useGeneratedKeys="true" keyProperty="id">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <insert id="insertMultiKeyTypes">
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <!-- DDL Auto 示例（需要 <entity> 的 ddlAuto 属性支持） -->
    <!-- 注意：这是示例，实际需要在 entity 中配置 ddlAuto="create" -->
    <insert id="insertDdlAutoUser">
        INSERT INTO auto_created_table (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <!-- 错误测试：无效的 keyType -->
    <insert id="insertInvalidKeyType">
        <!-- 这里故意配置无效的 keyType 用于测试错误处理 -->
        INSERT INTO user_info (name, age, create_time)
        VALUES (#{name}, #{age}, #{createTime})
    </insert>
    
    <!-- 错误测试：不存在的 Holder 类 -->
    <insert id="insertNonExistentHolder">
        <!-- keyType 配置了不存在的类名 -->
        INSERT INTO user_info (id, name, age, create_time)
        VALUES (#{id}, #{name}, #{age}, #{createTime})
    </insert>
    
</mapper>

=== zycgit/dbvisitor/dbvisitor-core/src/test/resources/net_hasor_db/dal_dynamic/execute/basic_execute.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.db.dal.execute.TestExecuteDal">
    <resultMap id="tb_user_resultMap" type="net.hasor.test.db.dto.TbUser2">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </resultMap>

    <sql id="user_do_allColumns">
        user_uuid,
        name,
        login_name,
        login_password,
        email,
        `index`,
        register_time
    </sql>

    <insert id="createUser">
        insert into test_user (
        <include refid="user_do_allColumns"/>
        ) values (
        #{uid},
        #{name},
        #{account},
        #{password},
        #{index},
        #{createTime}
        );
    </insert>

    <insert id="initUser">
        insert into test_user (
        <include refid="user_do_allColumns"/>
        )
        values ('11', '12', '13', '14', '15', 16, '2021-07-20 00:00:00'),
        ('21', '22', '23', '24', '25', 26, '2021-07-20 00:00:00');
    </insert>

    <select id="listUserList_1"  resultMap="tb_user_resultMap" statementType="PREPARED">
        select
        <include refid="user_do_allColumns"/>
        from test_user;
    </select>

    <select id="listUserList_2" resultType="net.hasor.test.db.dal.execute.TestUser" statementType="STATEMENT">
        select
        <include refid="user_do_allColumns"/>
        from test_user;
    </select>

    <select id="callSelectUser" statementType="CALLABLE">
        {call proc_select_user(#{abc, mode=out})}
    </select>

    <insert id="insertAutoID_1">
        insert into auto_id (
            userUUID, name
        ) values (
            #{uid}, #{name}
        );
        <selectKey keyProperty="id" order="AFTER" resultType="java.lang.Integer">
            SELECT LAST_INSERT_ID()
        </selectKey>
    </insert>

    <insert id="insertAutoID_2">
        insert into auto_id (
            userUUID, name
        ) values (
            #{uid}, #{name}
        );
        <selectKey keyProperty="id" keyColumn="cc" order="AFTER">
            SELECT LAST_INSERT_ID() as cc
        </selectKey>
    </insert>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/redis/RefEntityMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisXmlRefMapperDao">
    <select id="selectByAgeRange" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZRANGEBYSCORE @{macro, redisAges} #{range.minAge} #{range.maxAge} </select>
    <select id="selectByBean" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZRANGEBYSCORE #{user.name} #{user.age} +inf </select>
    <select id="selectByIds" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZUNION #{ids.size()} <foreach collection="ids" item="item" separator=" " open=" " close=" ">@{macro, redisRecordKey}</foreach> </select>
    <select id="selectWithOrderBy" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZRANGE ${orderColumn} 0 -1 </select>
    <select id="selectAsMaps" resultType="java.util.Map">ZRANGE @{macro, redisOwners} 0 -1 WITHSCORES</select>
    <select id="insertUser" resultSetExtractor="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisIntegerResultExtractor"> EVAL "local u=cjson.decode(ARGV[1]); redis.call('ZADD',KEYS[1],u.id,ARGV[1]); redis.call('ZADD',KEYS[2],u.age,ARGV[1]); redis.call('HSET',KEYS[3],u.name..':'..u.age,ARGV[1]); return 1" 3 @{macro, redisUsers} @{macro, redisAges} @{macro, redisNames} #{#{'id':id,'name':name,'age':age,'email':email,'createTime':1L},typeHandler=net.hasor.dbvisitor.types.handler.json.JsonTypeHandler} </select>
    <select id="updateEmail" resultSetExtractor="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisIntegerResultExtractor"> EVAL "local rows=redis.call('ZRANGEBYSCORE',KEYS[1],ARGV[1],ARGV[1]); if #rows==0 then return 0 end; local old=rows[1]; local u=cjson.decode(old); u.email=ARGV[2]; local new=cjson.encode(u); redis.call('ZREM',KEYS[1],old); redis.call('ZREM',KEYS[2],old); redis.call('ZADD',KEYS[1],u.id,new); redis.call('ZADD',KEYS[2],u.age,new); redis.call('HSET',KEYS[3],u.name..':'..u.age,new); return 1" 3 @{macro, redisUsers} @{macro, redisAges} @{macro, redisNames} #{id} #{email} </select>
    <select id="deleteById" resultSetExtractor="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisIntegerResultExtractor"> EVAL "local rows=redis.call('ZRANGEBYSCORE',KEYS[1],ARGV[1],ARGV[1]); if #rows==0 then return 0 end; local old=rows[1]; local u=cjson.decode(old); redis.call('ZREM',KEYS[1],old); redis.call('ZREM',KEYS[2],old); redis.call('HDEL',KEYS[3],u.name..':'..u.age); return 1" 3 @{macro, redisUsers} @{macro, redisAges} @{macro, redisNames} #{id} </select>
    <select id="selectById" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZRANGEBYSCORE @{macro, redisUsers} #{id} #{id} </select>
    <select id="selectAll" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZRANGE @{macro, redisUsers} 0 -1 </select>
    <select id="queryUsersByAge" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZRANGEBYSCORE @{macro, redisAges} #{age} #{age} </select>
    <select id="countUsers" resultType="int">ZCARD @{macro, redisUsers}</select>
    <select id="queryUsersByCondition" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> HGET @{macro, redisNames} #{name + ':' + age} </select>
    <select id="queryUserByBean" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> HGET @{macro, redisNames} #{name + ':' + age} </select>
    <select id="insertOrder" resultSetExtractor="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisIntegerResultExtractor"> EVAL "local o=cjson.decode(ARGV[1]); redis.call('ZADD',KEYS[1],o.id,ARGV[1]); redis.call('ZADD',KEYS[2],o.userId,ARGV[1]); return 1" 2 @{macro, redisOrders} @{macro, redisOwners} #{#{'id':id,'userId':userId,'orderNo':orderNo,'amount':amount},typeHandler=net.hasor.dbvisitor.types.handler.json.JsonTypeHandler} </select>
    <select id="deleteOrderById" resultSetExtractor="net.hasor.dbvisitor.test.realdb.redis.api.mapper.RedisIntegerResultExtractor"> EVAL "local rows=redis.call('ZRANGEBYSCORE',KEYS[1],ARGV[1],ARGV[1]); if #rows==0 then return 0 end; redis.call('ZREM',KEYS[1],rows[1]); redis.call('ZREM',KEYS[2],rows[1]); return 1" 2 @{macro, redisOrders} @{macro, redisOwners} #{id} </select>
    <select id="queryOrdersByUserId" resultType="net.hasor.dbvisitor.test.contract.material.model.UserOrder" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> ZRANGEBYSCORE @{macro, redisOwners} #{userId} #{userId} </select>
</mapper>
