=== zycgit/dbvisitor/dbvisitor-doc/static/schema/dbvisitor-mapper.dtd
<?xml version="1.0" encoding="UTF-8" ?>
<!--
       Copyright 2015-2022 the original author or authors.

       Licensed under the Apache License, Version 2.0 (the "License");
       you may not use this file except in compliance with the License.
       You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

       Unless required by applicable law or agreed to in writing, software
       distributed under the License is distributed on an "AS IS" BASIS,
       WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
       See the License for the specific language governing permissions and
       limitations under the License.
-->
<!ELEMENT mapper ( resultMap* | entity* | sql* | execute* | insert* | update* | delete* | select* )+>
<!ATTLIST mapper
        namespace CDATA #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        >

<!ELEMENT resultMap (result*)>
<!ATTLIST resultMap
        id CDATA #IMPLIED
        type CDATA #REQUIRED
        caseInsensitive (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        autoMapping (true|false) #IMPLIED
        >

<!ELEMENT result EMPTY>
<!ATTLIST result
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        >

<!ELEMENT entity (id*,mapping*,index*)>
<!ATTLIST entity
        id CDATA #IMPLIED
        catalog CDATA #IMPLIED
        schema CDATA #IMPLIED
        table CDATA #IMPLIED
        type CDATA #REQUIRED
        autoMapping (true|false) #IMPLIED
        useDelimited (true|false) #IMPLIED
        mapUnderscoreToCamelCase (true|false) #IMPLIED
        caseInsensitive (true|false) #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        ddlAuto (none|create|add|update|create-drop) #IMPLIED
        >

<!ELEMENT id EMPTY>
<!ATTLIST id
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        orderByColTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT mapping EMPTY>
<!ATTLIST mapping
        column CDATA #REQUIRED
        property CDATA #REQUIRED
        javaType CDATA #IMPLIED
        jdbcType CDATA #IMPLIED
        typeHandler CDATA #IMPLIED
        keyType CDATA #IMPLIED
        insert (true|false) #IMPLIED
        update (true|false) #IMPLIED
        selectTemplate CDATA #IMPLIED
        insertTemplate CDATA #IMPLIED
        setColTemplate CDATA #IMPLIED
        setValueTemplate CDATA #IMPLIED
        whereColTemplate CDATA #IMPLIED
        whereValueTemplate CDATA #IMPLIED
        groupByColTemplate CDATA #IMPLIED
        orderByColTemplate CDATA #IMPLIED
        sqlType CDATA #IMPLIED
        length CDATA #IMPLIED
        precision CDATA #IMPLIED
        scale CDATA #IMPLIED
        character-set CDATA #IMPLIED
        collation CDATA #IMPLIED
        nullable (true|false) #IMPLIED
        default CDATA #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT index (column* | EMPTY)>
<!ATTLIST index
        name CDATA #REQUIRED
        columns CDATA #IMPLIED
        unique (true|false) #IMPLIED
        comment CDATA #IMPLIED
        other CDATA #IMPLIED
        >

<!ELEMENT column (#PCDATA)>

<!ELEMENT insert (#PCDATA | selectKey | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST insert
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        useGeneratedKeys CDATA #IMPLIED
        generatedKeySource CDATA #IMPLIED
        keyProperty CDATA #IMPLIED
        keyColumn CDATA #IMPLIED
        >

<!ELEMENT update (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST update
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT delete (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST delete
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        >

<!ELEMENT execute (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST execute
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        bindOut CDATA #IMPLIED
        >

<!ELEMENT select (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST select
        id CDATA #REQUIRED
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType (FORWARD_ONLY | SCROLL_INSENSITIVE | SCROLL_SENSITIVE | DEFAULT) #IMPLIED
        resultMap CDATA #IMPLIED
        resultType CDATA #IMPLIED
        resultSetExtractor CDATA #IMPLIED
        resultRowCallback CDATA #IMPLIED
        resultRowMapper CDATA #IMPLIED
        resultTypeHandler CDATA #IMPLIED
        bindOut CDATA #IMPLIED
        >

<!ELEMENT sql (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST sql
        id CDATA #REQUIRED
        >

<!-- Dynamic -->
<!ELEMENT selectKey (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
    <!ATTLIST selectKey
        statementType (STATEMENT|PREPARED|CALLABLE) #IMPLIED
        timeout CDATA #IMPLIED
        fetchSize CDATA #IMPLIED
        resultSetType CDATA #IMPLIED
        keyProperty CDATA #REQUIRED
        keyColumn CDATA #IMPLIED
        order (BEFORE|AFTER) #REQUIRED
        >

<!ELEMENT include EMPTY>
<!ATTLIST include
        refid CDATA #REQUIRED
        >

<!ELEMENT trim (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST trim
        prefix CDATA #IMPLIED
        prefixOverrides CDATA #IMPLIED
        suffix CDATA #IMPLIED
        suffixOverrides CDATA #IMPLIED
        >

<!ELEMENT where (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT set (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT foreach (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST foreach
        collection CDATA #REQUIRED
        item CDATA #REQUIRED
        index CDATA #IMPLIED
        open CDATA #IMPLIED
        close CDATA #IMPLIED
        separator CDATA #IMPLIED
        >

<!ELEMENT choose (when* , otherwise?)>

<!ELEMENT when (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST when
        test CDATA #REQUIRED
        >

<!ELEMENT otherwise (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>

<!ELEMENT if (#PCDATA | include | trim | where | set | foreach | choose | if | bind)*>
<!ATTLIST if
        test CDATA #REQUIRED
        >

<!ELEMENT bind EMPTY>
<!ATTLIST bind
        name CDATA #REQUIRED
        value CDATA #REQUIRED
        >

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/XmlStatementAttrMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.StatementAttrMapper">

    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <!-- 默认 PREPARED 类型 -->
    <select id="selectPrepared" resultMap="userResultMap">
        SELECT * FROM user_info WHERE id = #{id}
    </select>

    <!-- 显式 PREPARED 类型 -->
    <select id="selectExplicitPrepared" resultMap="userResultMap" statementType="PREPARED">
        SELECT * FROM user_info WHERE id = #{id}
    </select>

    <!-- STATEMENT 类型（非预编译） -->
    <select id="selectStatement" resultMap="userResultMap" statementType="STATEMENT">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- timeout 超时设置 -->
    <select id="selectWithTimeout" resultMap="userResultMap" timeout="30">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- fetchSize 设置 -->
    <select id="selectWithFetchSize" resultMap="userResultMap" fetchSize="2">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- resultSetType 设置 -->
    <select id="selectForwardOnly" resultMap="userResultMap" resultSetType="FORWARD_ONLY">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <select id="selectScrollInsensitive" resultMap="userResultMap" resultSetType="SCROLL_INSENSITIVE">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- 组合属性 -->
    <select id="selectCombined" resultMap="userResultMap"
            statementType="PREPARED" timeout="30" fetchSize="10" resultSetType="FORWARD_ONLY">
        SELECT * FROM user_info WHERE name LIKE 'StmtAttr%' ORDER BY id
    </select>

    <!-- insert 的 statementType（使用默认 PREPARED 但显式标注） -->
    <insert id="insertWithStatement" statementType="PREPARED">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/mssql/material/XmlKeyGenerationMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.KeyGenerationMapper">

    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <insert id="insertWithGeneratedKeys"
            useGeneratedKeys="true"
            keyProperty="id"
            keyColumn="id"
            generatedKeySource="resultSet">
        INSERT INTO user_info (name, age, email, create_time)
        OUTPUT INSERTED.id
        VALUES (#{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <insert id="insertWithKeyColumn"
            useGeneratedKeys="true"
            keyProperty="id"
            keyColumn="id"
            generatedKeySource="resultSet">
        INSERT INTO user_info (name, age, email, create_time)
        OUTPUT INSERTED.id
        VALUES (#{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <insert id="insertWithGeneratedKeyResultSet"
            useGeneratedKeys="true"
            keyProperty="id"
            keyColumn="id"
            generatedKeySource="resultSet">
        INSERT INTO user_info (name, age, email, create_time)
        OUTPUT INSERTED.id
        VALUES (#{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <insert id="insertWithSelectKeyBefore">
        <selectKey keyProperty="id" order="BEFORE">
            SELECT NEXT VALUE FOR user_info_id_seq
        </selectKey>
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <insert id="insertWithSelectKeyAfter">
        <selectKey keyProperty="id" order="AFTER">
            SELECT CONVERT(INT, current_value) FROM sys.sequences WHERE name = 'user_info_id_seq'
        </selectKey>
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (NEXT VALUE FOR user_info_id_seq, #{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <insert id="insertWithExplicitId">
        INSERT INTO user_info (id, name, age, email, create_time)
        VALUES (#{id}, #{name}, #{age}, #{email}, @{macro, currentTimestamp})
    </insert>

    <select id="selectById" resultMap="userResultMap">
        SELECT * FROM user_info WHERE id = #{id}
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/realdb/milvus/mapper/SharedResultHandlerMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.ResultHandlerMapper">

    <resultMap id="userResultMap" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <result column="name" property="name"/>
        <result column="age" property="age"/>
        <result column="email" property="email"/>
        <result column="create_time" property="createTime"/>
    </resultMap>

    <insert id="insertUser">
        INSERT INTO user_info (id, name, age, email, create_time, v)
        VALUES (#{id}, #{name}, #{age}, #{email}, '2023-11-14 22:13:20.123', [10, 0])
    </insert>

    <!-- resultType：实体类 -->
    <select id="selectByResultType" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        SELECT id, name, age, email, create_time FROM user_info WHERE name LIKE 'ResHdl%' AND age &gt; #{minAge} ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

    <!-- resultType：map -->
    <select id="selectByResultTypeMap" resultType="map">
        SELECT id, name, age, email, create_time FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

    <!-- resultType：int -->
    <select id="countByResultType" resultType="int">
        SELECT COUNT(*) FROM user_info WHERE name LIKE 'ResHdl%'
    </select>

    <select id="countByResultTypeLong" resultType="long">
        SELECT COUNT(*) FROM user_info WHERE name LIKE 'ResHdl%'
    </select>

    <!-- resultType：string -->
    <select id="selectNamesByResultType" resultType="string">
        SELECT name FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

    <!-- resultMap -->
    <select id="selectByResultMap" resultMap="userResultMap">
        SELECT id, name, age, email, create_time FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

    <!-- resultRowMapper：ColumnMapRowMapper -->
    <select id="selectByColumnMapRowMapper"
            resultRowMapper="net.hasor.dbvisitor.test.contract.material.handler.ResultHandlerProbe$ColumnMapMapper">
        SELECT id, name, age, email, create_time FROM user_info WHERE name LIKE 'ResHdl%'
        <if test="minAge != null">AND age &gt; #{minAge}</if>
        ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

    <select id="selectByRowCallback"
            resultRowCallback="net.hasor.dbvisitor.test.contract.api.mapper.xml.XmlMapperResultHandlerCase$CountingCallback">
        SELECT id, name, age, email, create_time FROM user_info WHERE name LIKE 'ResHdl%'
        <if test="minAge != null">AND age &gt; #{minAge}</if>
        ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

    <!-- resultSetExtractor：ColumnMapResultSetExtractor -->
    <select id="selectByColumnMapExtractor"
            resultSetExtractor="net.hasor.dbvisitor.test.contract.material.handler.ResultHandlerProbe$ColumnMapExtractor">
        SELECT id, name, age, email, create_time FROM user_info WHERE name LIKE 'ResHdl%'
        <if test="minAge != null">AND age &gt; #{minAge}</if>
        ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

    <!-- resultSetExtractor：PairsResultSetExtractor -->
    <select id="selectIdNamePairs"
            resultSetExtractor="net.hasor.dbvisitor.jdbc.extractor.PairsResultSetExtractor">
        SELECT id, name FROM user_info WHERE name LIKE 'ResHdl%' ORDER BY v &lt;-&gt; [0, 0] LIMIT 100
    </select>

</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapping/write_policy_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="net.hasor.test.xml.writepolicy">

    <!-- insert="false": name 列不参与 INSERT -->
    <entity id="InsertFalseEntity" table="user_info_if" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" insert="false"/>
        <mapping column="age" property="age"/>
    </entity>

    <!-- update="false": name 列不参与 UPDATE -->
    <entity id="UpdateFalseEntity" table="user_info_uf" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" update="false"/>
        <mapping column="age" property="age"/>
    </entity>

    <!-- insert="false" update="false": name 列完全只读 -->
    <entity id="BothFalseEntity" table="user_info_bf" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name" insert="false" update="false"/>
        <mapping column="age" property="age"/>
    </entity>

    <!-- 默认策略: 不指定 insert/update → 均为 true -->
    <entity id="DefaultPolicyEntity" table="user_info_dp" type="net.hasor.dbvisitor.test.contract.material.model.UserInfo">
        <id column="id" property="id"/>
        <mapping column="name" property="name"/>
        <mapping column="age" property="age"/>
    </entity>

</mapper>

=== zycgit/dbvisitor/dbvisitor-core/src/test/resources/net_hasor_db/dal_repository/mapper_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="resultMap_test">
    <resultMap id="blobResourceDO" type="net.hasor.test.db.dto.TB_User" autoMapping="true">
        <id column="id" property="id"/>
        <result column="gmt_create" property="gmtCreate"/>
        <result column="gmt_modified" property="gmtModified"/>
        <result column="instance_id" property="instanceId"/>
        <result column="owner_name" property="ownerName"/>
        <result column="owner_type" property="ownerType" javaType="com.clougence.clouddm.console.web.constants.ResourceType"/>
        <result column="blob_type" property="blobType" javaType="com.clougence.clouddm.console.web.constants.SecurityFileType"/>
        <result column="content" property="content"/>
    </resultMap>

    <resultMap id="blobResourceDO" type="net.hasor.test.db.dto.TB_User" autoMapping="true">
        <id column="id" property="id"/>
        <result column="gmt_create" property="gmtCreate"/>
        <result column="gmt_modified" property="gmtModified"/>
        <result column="instance_id" property="instanceId"/>
        <result column="owner_name" property="ownerName"/>
        <result column="owner_type" property="ownerType" javaType="com.clougence.clouddm.console.web.constants.ResourceType"/>
        <result column="blob_type" property="blobType" javaType="com.clougence.clouddm.console.web.constants.SecurityFileType"/>
        <result column="content" property="content"/>
    </resultMap>
</mapper>

=== zycgit/dbvisitor/dbvisitor-core/src/test/resources/net_hasor_db/dal_repository/mapper_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN" "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper autoMapping="true">
    <resultMap id="mapper_2" type="net.hasor.test.db.dto.TbUser"/>

    <resultMap id="mapper_3" type="net.hasor.test.db.dto.TbUser2"/>

    <resultMap id="mapper_4" type="net.hasor.test.db.dto.TbUser2" autoMapping="false">
        <id column="user_uuid" property="uid"/>
        <result column="name" property="name"/>
        <result column="login_name" property="account"/>
        <result column="login_password" property="password"/>
        <result column="email" property="mail"/>
        <result column="index" property="index" javaType="int"/>
        <result column="register_time" property="createTime"/>
    </resultMap>

    <resultMap id="mapper_5" type="net.hasor.test.db.dto.TbUser2" mapUnderscoreToCamelCase="true"/>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/redis/ResultHandlerMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.ResultHandlerMapper">
    <resultMap id="member" type="net.hasor.dbvisitor.test.realdb.redis.api.jdbc.RedisJdbcFixture$ScoredMember" autoMapping="false">
        <result column="ELEMENT" property="element"/>
        <result column="SCORE" property="score" javaType="java.lang.Double"/>
    </resultMap>
    <sql id="members"> ZRANGEBYSCORE @{macro, redisAges} #{minAge == null ? 0 : minAge} +inf WITHSCORES </sql>
    <select id="selectByResultType" resultType="net.hasor.dbvisitor.test.realdb.redis.api.jdbc.RedisJdbcFixture$ScoredMember"><include refid="members"/></select>
    <select id="selectByResultTypeMap" resultType="java.util.Map"><include refid="members"/></select>
    <select id="selectByResultMap" resultMap="member"><include refid="members"/></select>
    <select id="selectByColumnMapRowMapper" resultRowMapper="net.hasor.dbvisitor.test.contract.material.handler.ResultHandlerProbe$ColumnMapMapper"><include refid="members"/></select>

    <select id="selectByRowCallback" resultRowCallback="net.hasor.dbvisitor.test.contract.api.mapper.xml.XmlMapperResultHandlerCase$CountingCallback"><include refid="members"/></select>
    <select id="selectByColumnMapExtractor" resultSetExtractor="net.hasor.dbvisitor.test.contract.material.handler.ResultHandlerProbe$ColumnMapExtractor"><include refid="members"/></select>
    <select id="selectIdNamePairs" resultSetExtractor="net.hasor.dbvisitor.jdbc.extractor.PairsResultSetExtractor"><include refid="members"/></select>
    <select id="countByResultType" resultType="java.lang.Integer">ZCARD @{macro, redisAges}</select>
    <select id="countByResultTypeLong" resultType="java.lang.Long">ZCARD @{macro, redisAges}</select>
    <select id="selectNamesByResultType" resultType="java.lang.String">ZRANGE @{macro, redisAges} 0 -1</select>
</mapper>

=== zycgit/dbvisitor/dbvisitor-test/src/test/resources/mapper/redis/SelectKeyMapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//dbvisitor.net//DTD Mapper 1.0//EN"
        "https://www.dbvisitor.net/schema/dbvisitor-mapper.dtd">
<mapper namespace="xmltest.KeyGenerationMapper">
    <sql id="entity"> #{#{'name':name,'age':age,'email':email},typeHandler=net.hasor.dbvisitor.types.handler.json.JsonTypeHandler} </sql>
    <insert id="insertWithSelectKeyBefore"> <selectKey keyProperty="id" order="BEFORE">INCR @{macro, redisCounter}</selectKey> RPUSH @{macro, redisUsers} <include refid="entity"/> </insert>
    <insert id="insertWithSelectKeyAfter"> <selectKey keyProperty="id" order="AFTER">LLEN @{macro, redisUsers}</selectKey> RPUSH @{macro, redisUsers} <include refid="entity"/> </insert>
    <select id="selectById" resultType="net.hasor.dbvisitor.test.contract.material.model.UserInfo" resultTypeHandler="net.hasor.dbvisitor.types.handler.json.JsonTypeHandler"> LRANGE @{macro, redisUsers} #{id - 1} #{id - 1} </select>
</mapper>
